#state:
#  s0:     Progress along lane (m)
#  v0:     Velocity (m/s)
#  delta:    Steering angle (rad)
#  t0:     Initial time (s) - string for decimal

state_0: &state
  x0: 0.0
  y0: 0.0
  theta: 0.0
  v0: 5.0
  delta: 0.0
  t0: "0.0"

state_1_lanker:
  x0: -7.0
  y0: -0.0
  v0: 6.0

state_2_lanker:
  <<: *state
  x0: 18.0
  y0: 10.0
  v0: 5.0

state_1_peach:
  <<: *state
  x0: 4.0
  y0: 0.0
  v0: 6.5

state_2_peach:
  <<: *state
  x0: -1.0
  y0: 25.0
  v0: 6.5

state_3_peach:
  <<: *state
  x0: 13.0
  y0: 14.0
  v0: 6.5

state_4_peach:
  <<: *state
  x0: -2.0
  y0: 30.0
  v0: 5.0

state_1_deu:
  <<: *state
  x0: 22.0
  y0: 0.0
  v0: 3.0
  theta: 0.0

state_2_deu:
  <<: *state
  x0: 110.0
  y0: 6.0
  v0: 5.0
  theta: -3.25

state_3_deu:
  <<: *state
  x0: 65.0
  y0: 44.0
  v0: 1.0
  theta: -1.50

state_3:
  <<: *state
  v0: 3.0

state_4:
  <<: *state
  v0: 3.0

state_5:
  <<: *state
  v0: 5.0

state_6:
  <<: *state
  v0: 6.0
