
#state:
#  s0:     Progress along lane (m)
#  v0:     Velocity (m/s)
#  st0:    Steering angle (rad)
#  t0:     Initial time (s) - string for decimal

state_1:    &state
  s0:     6.5
  th0:    0.0
  v0:     5.0
  st0:    0.0
  t0:     "0.0"

state_2:
  <<: *state
  s0:     10.0
  v0:     5.0

state_3:
  <<: *state
  s0:     10.0
  v0:     3.0

state_4:
  <<: *state
  s0:     12.0
  v0:     3.0
