
#state:
#  s0:     Progress along lane (m)
#  v0:     Velocity (m/s)
#  st0:    Steering angle (rad)
#  t0:     Initial time (s) - string for decimal

state_1:    &state
  x0:     -10.0
  y0:     -7.0
  th0:    0.0
  v0:     6.0
  st0:    0.0
  t0:     "0.0"

state_2:
  <<: *state
  x0:     30.0
  y0:     4.0
  v0:     5.0

state_3:
  <<: *state
  v0:     3.0

state_4:
  <<: *state
  v0:     3.0

state_5:
  <<: *state
  v0:     5.0

state_6:
  <<: *state
  v0:     6.0
