
#map_name:
#  direction1:     [List of Nodes]
#  direction2:     [List of Nodes]
#  ...
# Lane number: 1-right, 2-left

4way-double-intersection-only:
  down_left_1:      ['P30', 'P21', 'P8',  'P9' ]
  down_left_2:      ['P31', 'P20', 'P10', 'P11']
  right_left_2:     ['P27', 'P22', 'P10', 'P11']
  left_up_1:        ['P12', 'P13', 'P0',  'P1' ]
  left_up_2:        ['P14', 'P15', 'P2',  'P3' ]
  up_down_1:        ['P4',  'P5',  'P17', 'P28']
  down_right_1:     ['P30', 'P21', 'P18', 'P24']
  down_right_2:     ['P31', 'P20', 'P19', 'P25']

