
#map_name: Map to load (from scenarios)
#map_name: "USA_Lanker-1_1_T-1"
map_name:       "USA_Peach-4_3_T-1"

#max_length: Max reference lane length in m
max_length:     75.0

#plot_limits: null, "auto" or [[xmin, xmax], [ymin,ymax]]
plot_limits:    [[-30, 20], [-20, 30]]

#players:    List of players in the game
#  P1:        Player Name
#    state:    Initial state (from initial_states.yaml)
#    goals:    List of Goal(s) polygon points [[[xi,yi],[xj,yj]]] or null
#    traj:     Trajectory params (from trajectories.yaml)
#    pref:     Player preference (from player_pref.yaml)
#    vg:       Vehicle geometry (from vehicles.yaml)
#  P2: ...

basic:
  players:
    P1:
      state:    "state_1_peach"
      goals:    [[[0.0,22.0], [9.0,22.0], [9.0,27.0], [0.0,27.0]]]
      traj:     "traj_1_3"
      pref:     "pref_d6"
      vg:       "green_car"
    P2:
      state:    "state_2_peach"
      goals:    [[[1.0,-10.0], [-8.0,-10.0], [-8.0,-15.0], [1.0,-15.0]]]
      traj:     "traj_1_3"
      pref:     "pref_d6"
      vg:       "blue_car"
    P3:
      state:    "state_3_peach"
      goals:    [[[-18.0,9.0], [-23.0,9.0], [-23.0,18.0], [-18.0,18.0]]]
      traj:     "traj_1_3"
      pref:     "pref_d6"
      vg:       "red_car"

## Lexi config
lexi:
  players:
    P1:
      state:    "state_3"
      traj:     "traj_2"
      pref:     "NoPreference"
      lane:     ["lu2"]
      vg:       "red_bicycle"

  states:       ["state_5", "state_6"]
  prefs:        ["pref_8", "pref_9"]

## LF Players
lf:
  players:
    P1:
      state:    "state_1"
      traj:     "traj_1_r"
      pref:     "pref_d6"
      lane:     ["rl2"]
      vg:       "green_car"
    P2:
      state:    "state_2"
      traj:     "traj_1_rs"
      pref:     "pref_d6"
      lane:     ["dl2"]
      vg:       "blue_car"
