
# Pref structure for each player
# Player_name:
#   node1:   List[None]
#   node2:   List[Parent1, Parent2, ...]
#   node3:   List[Parent1, Parent3, ...]
#     nodes    -> Any node from pref_nodes.yaml
#     Parents  -> Any node from pref_nodes.yaml


## Finite time preferences
# Toy game preferences
pref_1:                       &pref_1
  CollisionEnergy:            []
  DrivableAreaViolation:      ["CollisionEnergy"]
  ProgressAlongReference:     ["DrivableAreaViolation"]
  LateralComfort:             ["DrivableAreaViolation"]

# Trajectory game preference
pref_2:                       &pref_2
  <<: *pref_1
  LongitudinalAcceleration:   ["ProgressAlongReference"]
  DeviationLateral:           ["LateralComfort", "LongitudinalAcceleration"]
  DeviationHeading:           ["LateralComfort", "LongitudinalAcceleration"]

# Comfort Preference
pref_3:                       &pref_3
  CollisionEnergy:            []
  DrivableAreaViolation:      ["CollisionEnergy"]
  LateralComfort:             ["DrivableAreaViolation"]
  LongitudinalAcceleration:   ["LateralComfort"]
  DeviationLateral:           ["LongitudinalAcceleration"]
  DeviationHeading:           ["LongitudinalAcceleration"]
  ProgressAlongReference:     ["LongitudinalAcceleration"]

# Racing preference
pref_4:                       &pref_4
  CollisionEnergy:            []
  DrivableAreaViolation:      ["CollisionEnergy"]
  ProgressAlongReference:     ["DrivableAreaViolation"]
  DeviationLateral:           ["ProgressAlongReference"]
  DeviationHeading:           ["ProgressAlongReference"]

# Weighted preference
pref_5:                       &pref_5
  weights_1:                  []

# Some Combination preference
pref_6:                       &pref_6
  CollisionEnergy:            []
  DrivableAreaViolation:      ["CollisionEnergy"]
  weights_5:                  ["DrivableAreaViolation"]
  LateralComfort:             ["weights_5"]
  LongitudinalAcceleration:   ["weights_5"]


## Finite distance preferences
# Toy game preferences
pref_d1:                      &pref_d1
  CollisionEnergy:            []
  weights_6:                  ["CollisionEnergy"]
  LateralComfort:             ["weights_6"]

# Trajectory game preference
pref_d2:                      &pref_d2
  <<: *pref_d1
  LongitudinalAcceleration:   ["weights_6"]
  MinimumClearance:           ["weights_6"]
  DeviationLateral:           ["LateralComfort", "LongitudinalAcceleration", "MinimumClearance"]
  DeviationHeading:           ["LateralComfort", "LongitudinalAcceleration", "MinimumClearance"]

# Comfort Preference
pref_d3:                      &pref_d3
  CollisionEnergy:            []
  DrivableAreaViolation:      ["CollisionEnergy"]
  LateralComfort:             ["DrivableAreaViolation"]
  LongitudinalAcceleration:   ["LateralComfort"]
  MinimumClearance:           ["LateralComfort"]
  DeviationLateral:           ["LongitudinalAcceleration", "MinimumClearance"]
  DeviationHeading:           ["LongitudinalAcceleration", "MinimumClearance"]
  EpisodeTime:                ["LongitudinalAcceleration", "MinimumClearance"]

# Racing preference
pref_d4:                      &pref_d4
  CollisionEnergy:            []
  DrivableAreaViolation:      ["CollisionEnergy"]
  weights_6:                  ["DrivableAreaViolation"]
  DeviationLateral:           ["weights_6"]
  MinimumClearance:           ["weights_6"]
  DeviationHeading:           ["DeviationLateral"]
  LongitudinalAcceleration:   ["DeviationHeading", "MinimumClearance"]

pref_d5:                      &pref_d5
  <<: *pref_5

pref_d6:                      &pref_d6
  CollisionEnergy:            []
  DrivableAreaViolation:      ["CollisionEnergy"]
  weights_6:                  ["DrivableAreaViolation"]
  weights_5:                  ["weights_6"]
  MinimumClearance:           ["weights_6"]
  LateralComfort:             ["weights_5", "MinimumClearance"]
  LongitudinalAcceleration:   ["weights_5", "MinimumClearance"]


pref_d7_1:                    &pref_d7_1
  CollisionEnergy:            []
  DrivableAreaViolation:      ["CollisionEnergy"]

pref_d7_2:                    &pref_d7_2
  <<: *pref_d7_1
  MinimumClearance:           ["DrivableAreaViolation"]

pref_d7_3:                    &pref_d7_3
  <<: *pref_d7_2
  EpisodeTime:                ["MinimumClearance"]
  LateralComfort:             ["MinimumClearance"]
  LongitudinalAcceleration:   ["MinimumClearance"]

pref_d7_4:                    &pref_d7_4
  <<: *pref_d7_2
  EpisodeTime:                ["MinimumClearance"]
  LateralComfort:             ["EpisodeTime"]
  LongitudinalAcceleration:   ["EpisodeTime"]

pref_d7_5:                    &pref_d7_5
  <<: *pref_d7_2
  LateralComfort:             ["MinimumClearance"]
  LongitudinalAcceleration:   ["LateralComfort"]
  EpisodeTime:                ["LateralComfort"]

pref_d7_6:                    &pref_d7_6
  <<: *pref_d7_2
  LongitudinalAcceleration:   ["MinimumClearance"]
  LateralComfort:             ["LongitudinalAcceleration"]
  EpisodeTime:                ["LongitudinalAcceleration"]

pref_d7_7:                    &pref_d7_7
  <<: *pref_d7_4
  DeviationLateral:           ["LateralComfort", "LongitudinalAcceleration"]
  DeviationHeading:           ["LateralComfort", "LongitudinalAcceleration"]

pref_d7:                      &pref_d7
  <<: *pref_d7_7

## Test preferences
test_1:                       &test_1
  CollisionEnergy:            []
  ProgressAlongReference:     ["CollisionEnergy"]
  DrivableAreaViolation:      ["CollisionEnergy"]
  LateralComfort:             ["CollisionEnergy"]
  DeviationLateral:           ["ProgressAlongReference"]

test_2:                       &test_2
  <<: *test_1
  DeviationHeading:           ["DeviationLateral"]
  MinimumClearance:           ["DrivableAreaViolation", "DeviationHeading"]
  LongitudinalAcceleration:   ["LateralComfort", "MinimumClearance"]

test_3:                       &test_3
  <<: *test_2
  EpisodeTime:                ["LateralComfort"]
  SteeringRate:               ["DrivableAreaViolation", "EpisodeTime"]
  SteeringAngle:              ["ProgressAlongReference", "SteeringRate"]
