
# Pref structure for each player
# Player_name:
#   node1:   List[None]
#   node2:   List[Parent1, Parent2, ...]
#   node3:   List[Parent1, Parent3, ...]
#     nodes    -> Any node from pref_nodes.yaml
#     Parents  -> Any node from pref_nodes.yaml


## Finite time preferences
# Toy game preferences
pref_1:                       &pref_1
  CollisionEnergy:            []
  DrivableAreaViolation:      ["CollisionEnergy"]
  ProgressAlongReference:     ["DrivableAreaViolation"]
  LateralComfort:             ["DrivableAreaViolation"]

# Trajectory game preference
pref_2:                       &pref_2
  <<: *pref_1
  LongitudinalJerk:           ["ProgressAlongReference"]
  DeviationLateral:           ["LateralComfort", "LongitudinalJerk"]
  DeviationHeading:           ["LateralComfort", "LongitudinalJerk"]

# Comfort Preference
pref_3:                       &pref_3
  CollisionEnergy:            []
  DrivableAreaViolation:      ["CollisionEnergy"]
  LateralComfort:             ["DrivableAreaViolation"]
  LongitudinalJerk:           ["LateralComfort"]
  DeviationLateral:           ["LongitudinalJerk"]
  DeviationHeading:           ["LongitudinalJerk"]
  ProgressAlongReference:     ["LongitudinalJerk"]

# Racing preference
pref_4:                       &pref_4
  CollisionEnergy:            []
  DrivableAreaViolation:      ["CollisionEnergy"]
  ProgressAlongReference:     ["DrivableAreaViolation"]
  DeviationLateral:           ["ProgressAlongReference"]
  DeviationHeading:           ["ProgressAlongReference"]

# Weighted preference
pref_5:                       &pref_5
  weights_1:                  []

# Some Combination preference
pref_6:                       &pref_6
  CollisionEnergy:            []
  DrivableAreaViolation:      ["CollisionEnergy"]
  weights_5:                  ["DrivableAreaViolation"]
  LateralComfort:             ["weights_5"]
  LongitudinalJerk:           ["weights_5"]


## Finite distance preferences
# Toy game preferences
pref_d1:                      &pref_d1
  CollisionEnergy:            []
  weights_6:                  ["CollisionEnergy"]
  LateralComfort:             ["weights_6"]

# Trajectory game preference
pref_d2:                      &pref_d2
  <<: *pref_d1
  LongitudinalJerk:           ["weights_6"]
  DeviationLateral:           ["LateralComfort", "LongitudinalJerk"]
  DeviationHeading:           ["LateralComfort", "LongitudinalJerk"]

# Comfort Preference
pref_d3:                      &pref_d3
  CollisionEnergy:            []
  LateralComfort:             ["CollisionEnergy"]
  LongitudinalJerk:           ["LateralComfort"]
  DeviationLateral:           ["LongitudinalJerk"]
  DeviationHeading:           ["LongitudinalJerk"]
  EpisodeTime:                ["LongitudinalJerk"]
  DrivableAreaViolation:      ["LongitudinalJerk"]

# Racing preference
pref_d4:                      &pref_d4
  CollisionEnergy:            []
  weights_6:                  ["CollisionEnergy"]
  DeviationLateral:           ["weights_6"]
  DeviationHeading:           ["weights_6"]

pref_d5:                      &pref_d5
  <<: *pref_5

pref_d6:                      &pref_d6
  CollisionEnergy:            []
  weights_6:                  ["CollisionEnergy"]
  weights_5:                  ["weights_6"]
  LateralComfort:             ["weights_5", "weights_6"]
  LongitudinalJerk:           ["weights_5", "weights_6"]


## Test preferences
test_1:                       &test_1
  CollisionEnergy:            []
  ProgressAlongReference:     ["CollisionEnergy"]
  DrivableAreaViolation:      ["CollisionEnergy"]
  LateralComfort:             ["CollisionEnergy"]
  DeviationLateral:           ["ProgressAlongReference"]

test_2:                       &test_2
  <<: *test_1
  DeviationHeading:           ["DeviationLateral"]
  LongitudinalJerk:           ["DrivableAreaViolation", "DeviationHeading"]
  LongitudinalAcceleration:   ["LateralComfort", "LongitudinalJerk"]

test_3:                       &test_3
  <<: *test_2
  EpisodeTime:                ["LateralComfort"]
  SteeringRate:               ["DrivableAreaViolation", "EpisodeTime"]
  SteeringAngle:              ["ProgressAlongReference", "SteeringRate"]
