
#map_name: Map to load (from worlds)
map_name: "4way-double-intersection-only"

#players:    List of players in the game
#  P1:        Player Name
#    state:    Initial state (from initial_states.yaml)
#    traj:     Trajectory params (from trajectories.yaml)
#    pref:     Player preference (from player_pref.yaml)
#    lane:     Lane to follow (from lanes.yaml for current map)
#    vg:       Vehicle geometry (from vehicles.yaml)
#  P2: ...

#players:
#  P1:
#    state:    "state_3"
#    traj:     "traj_2"
#    pref:     "pref_6"
#    lane:     "dl2"
#    vg:       "yellow_car"
#  P2:
#    state:    "state_2"
#    traj:     "traj_2"
#    pref:     "pref_2"
#    lane:     "rl2"
#    vg:       "blue_car"
#  P3:
#    state:    "state_1"
#    traj:     "traj_2"
#    pref:     "pref_3"
#    lane:     "lu2"
#    vg:       "green_car"
#  P4:
#    state:    "state_1"
#    traj:     "traj_2"
#    pref:     "pref_4"
#    lane:     "dr1"
#    vg:       "red_bicycle"
#  P5:
#    state:    "state_1"
#    traj:     "traj_2"
#    pref:     "pref_4"
#    lane:     "ud1"
#    vg:       "red_bicycle"

# Finite distance players
players:
  P1:
    state:    "state_3"
    traj:     "traj_2"
    pref:     "pref_d6"
    lane:     "dl2"
    vg:       "yellow_car"
#  P2:
#    state:    "state_1"
#    traj:     "traj_2"
#    pref:     "pref_d2"
#    lane:     "rl2"
#    vg:       "blue_car"
#  P3:
#    state:    "state_3"
#    traj:     "traj_2"
#    pref:     "pref_9"
#    lane:     "lu2"
#    vg:       "green_car"
#  P4:
#    state:    "state_1"
#    traj:     "traj_2"
#    pref:     "pref_d4"
#    lane:     "dr1"
#    vg:       "red_bicycle"
  P5:
    state:    "state_1"
    traj:     "traj_2"
    pref:     "pref_d4"
    lane:     "ud1"
    vg:       "red_bicycle"
#  P1:
#    state:    "state_1"
#    traj:     "traj_2"
#    pref:     "pref_10_1"
#    lane:     "rl2"
#    vg:       "blue_car"
#  P2:
#    state:    "state_2"
#    traj:     "traj_2"
#    pref:     "pref_10_i"
#    lane:     "ud2"
#    vg:       "red_car"
