
#map_name: Map to load (from worlds)
map_name: "4way-double-intersection-only"

#players:    List of players in the game
#  P1:        Player Name
#    state:    Initial state (from initial_states.yaml)
#    traj:     Trajectory params (from trajectories.yaml)
#    pref:     Player preference (from player_pref.yaml)
#    lane:     Lane to follow (from lanes.yaml for current map)
#    vg:       Vehicle geometry (from vehicles.yaml)
#  P2: ...

players:
  P1:
    state:    "state_1"
    traj:     "traj_1_rs"
#    traj:     "traj_1_rssolve"
    pref:     "pref_d6"
#    pref:     "pref_vio"
    lane:     ["rl2"]
#    lane:     ["rl2", "rl4"]
    vg:       "green_car"
  P2:
    state:    "state_2"
    traj:     "traj_1_rs"
#    traj:     "traj_1_rssolve"
    pref:     "pref_d6"
#    pref:     "pref_vio"
    lane:     ["dl2"]
    vg:       "blue_car"
#  P3:
#    state:    "state_3"
#    traj:     "traj_1_3"
#    pref:     "pref_9"
#    lane:     ["lu2"]
#    vg:       "yellow_car"
#  P4:
#    state:    "state_3"
#    traj:     "traj_1_3"
#    pref:     "pref_d4"
##    lane:     ["ud1", "ud3"]
#    lane:     ["ud1"]
#    vg:       "red_bicycle"
