
#weights:                      Weights for all the metrics (Missing taken as zero)
#  SurvivalTime:               weight
#  DeviationLateral:           weight
#  DeviationHeading:           weight
#  DrivableAreaViolation:      weight
#  ProgressAlongReference:     weight
#  LongitudinalAcceleration:   weight
#  LongitudinalJerk:           weight
#  LateralComfort:             weight
#  SteeringAngle:              weight
#  SteeringRate:               weight
#  CollisionEnergy:            weight

# pref_1.pref
weights_1:
  DrivableAreaViolation:      5.0
  ProgressAlongReference:     2.0
  LateralComfort:             2.0
  CollisionEnergy:            10.0

# pref_2.pref
weights_2:
  DeviationLateral:           0.5
  DeviationHeading:           0.5
  DrivableAreaViolation:      5.0
  ProgressAlongReference:     2.0
  LongitudinalJerk:           1.0
  LateralComfort:             2.0
  CollisionEnergy:            10.0

# pref_3.pref
weights_3:
  DeviationLateral:           0.5
  DeviationHeading:           0.5
  DrivableAreaViolation:      5.0
  ProgressAlongReference:     0.5
  LongitudinalJerk:           1.0
  LateralComfort:             2.0
  CollisionEnergy:            10.0

# pref_4.pref
weights_4:
  DeviationLateral:           0.5
  DeviationHeading:           0.5
  DrivableAreaViolation:      5.0
  ProgressAlongReference:     2.0
  CollisionEnergy:            10.0
