
#weights:                      Weights for all the metrics
#  EpisodeTime:               weight
#  DeviationLateral:           weight
#  DeviationHeading:           weight
#  DrivableAreaViolation:      weight
#  ProgressAlongReference:     weight
#  LongitudinalAcceleration:   weight
#  LateralComfort:             weight
#  SteeringAngle:              weight
#  SteeringRate:               weight
#  CollisionEnergy:            weight
#  MinimumClearance:           weight

## Raw metric nodes
EpisodeTime:
  EpisodeTime:             1.0
DeviationLateral:
  DeviationLateral:         1.0
DeviationHeading:
  DeviationHeading:         1.0
DrivableAreaViolation:
  DrivableAreaViolation:    1.0
ProgressAlongReference:
  ProgressAlongReference:   1.0
LongitudinalAcceleration:
  LongitudinalAcceleration: 1.0
LateralComfort:
  LateralComfort:           1.0
SteeringAngle:
  SteeringAngle:            1.0
SteeringRate:
  SteeringRate:             1.0
CollisionEnergy:
  CollisionEnergy:          1.0
MinimumClearance:
  MinimumClearance:         1.0

## Combination metric nodes
# pref_1
weights_1:
  DrivableAreaViolation:      5.0
  ProgressAlongReference:     2.0
  LateralComfort:             2.0
  CollisionEnergy:            10.0

# pref_2
weights_2:
  DeviationLateral:           0.5
  DeviationHeading:           0.5
  DrivableAreaViolation:      5.0
  ProgressAlongReference:     2.0
  LongitudinalAcceleration:   1.0
  LateralComfort:             2.0
  CollisionEnergy:            10.0

# pref_3
weights_3:
  DeviationLateral:           0.5
  DeviationHeading:           0.5
  DrivableAreaViolation:      5.0
  ProgressAlongReference:     0.5
  LongitudinalAcceleration:   1.0
  LateralComfort:             2.0
  CollisionEnergy:            10.0

# pref_4
weights_4:
  DeviationLateral:           0.5
  DeviationHeading:           0.5
  DrivableAreaViolation:      5.0
  ProgressAlongReference:     2.0
  CollisionEnergy:            10.0

weights_5:
  DeviationLateral:           0.5
  DeviationHeading:           0.5
  ProgressAlongReference:     2.0

# Time + area violation
weights_6:
  EpisodeTime:                1.0
  DrivableAreaViolation:      0.4
