
# All vehicles
#vehicle_name:
#  m:      Mass (kg)
#  w:      Width (m)
#  l:      Length (m)
#  colour: Colour (one from list at the bottom)

red_car:      &car
  m:      1000
  w:      0.9
  l:      1.9
  colour: "firebrick"

blue_car:
  <<: *car
  colour: "royalblue"

green_car:
  <<: *car
  colour: "forestgreen"

yellow_car:
  <<: *car
  colour: "yellow"

red_truck:    &truck
  m:      3000
  w:      2.0
  l:      3.0
  colour: "red"

blue_truck:
  <<: *truck
  colour: "blue"

red_bicycle:  &bicycle
  m:      80
  w:      0.25
  l:      0.5
  colour: "red"

#colours -> [R, G, B]
colours:
  red:      [1.0, 0.0, 0.0]
  green:    [0.0, 0.6, 0.0]
  blue:     [0.0, 0.0, 1.0]
  yellow:   [1.0, 0.7, 0.0]
