from enum import IntEnum, unique


@unique
class IdxInputB(IntEnum):
    """binary variables and auxiliary variables"""
    Sigma_L = 0
    """binary variable indicating whether vehicle is to the left of the obstacle"""
    Sigma_R = 1
    """binary variable indicating whether vehicle is to the right of the obstacle"""
    Sigma_B = 2
    """binary variable indicating whether vehicle is below the obstacle"""
    Sigma_A = 3
    """binary variable indicating whether vehicle is to the left of the obstacle"""
    Slack_L = 4
    """slack variable for sigma_L"""
    Slack_R = 5
    """slack variable for sigma_R"""
    Slack_B = 6
    """slack variable for sigma_B"""
    Slack_A = 7
    """slack variable for sigma_A"""


@unique
class IdxInputC(IntEnum):
    """continuous variable"""
    ddS = 8
    """lateral acc"""


@unique
class IdxState(IntEnum):
    S = 9
    """x-position in world frame"""
    dS = 10


@unique
class IdxParams(IntEnum):
    Homotopy = 0
    """homotopy class"""
    Box = 1
    """bos position and size generated by intersection"""
    TargetSpeed = 2
    """"target longitudinal speed in [m/s]"""
