#map_name: Map to load (from scenarios)
#map_name: "USA_Lanker-1_1_T-1"
map_name: "USA_Peach-4_3_T-1"

# Goal params
#max_length: Max reference lane length in m
goal:
  max_length: 75.0
  long_dist: 2.0
  lat_dist: 10.0

#plot_limits: null, "auto" or [[xmin, xmax], [ymin,ymax]]
plot_limits: [ [ -20, 20 ], [ -10, 30 ] ]

#players:    List of players in the game
#  P1:        Player Name
#    state:    Initial state (from initial_states.yaml)
#    goals:    List of Goal(s) polygon points [[[xi,yi],[xj,yj]]] or null
#    traj:     Trajectory params (from trajectories.yaml)
#    pref:     Player preference (from player_pref.yaml)
#    vg:       Vehicle geometry (from vehicles.yaml)
#  P2: ...

ral_01_level_0:
  players:
    Ambulance: &P1
      state: "state_1_peach"
      goals: [ [ -15.0,13.5 ], [ -15.0,17 ] ]
      traj: "traj_1_3"
      pref: "pref_ambulance"
      vg: "red_car"
    Granny: &P2
      state: "state_2_peach"
      goals: [ [ -3.5,-5.0 ], [ -7.0,-5.0 ] ]
      traj: "traj_1_3"
      pref: "pref_granny"
      vg: "green_car"
    Average: &P3
      state: "state_3_peach"
      goals: [ [ -15.0,13.5 ], [ -15.0,17 ] ]
      traj: "traj_1_3"
      pref: "common_person"
      vg: "blue_car"

# make sure the preferences here are a refinement of the ones above
ral_01_level_1:
  players:
    Ambulance:
      <<: *P1
      pref: "pref_ambulance_level_1"
    Granny:
      <<: *P2
      pref: "pref_granny"
    Average:
      <<: *P3
      pref: "common_person"


# make sure the preferences here are a refinement of the ones above
ral_01_level_2:
  players:
    Ambulance:
      <<: *P1
      pref: "pref_ambulance_level_2"
    Granny:
      <<: *P2
      pref: "pref_granny"
    Average:
      <<: *P3
      pref: "common_person"

####################################################################################

ral_02_level_0:
  players:
    Ambulance: &P12
      state: "state_1_peach"
      goals: [ [ -15.0,13.5 ], [ -15.0,17 ] ]
      traj: "traj_1_3"
      pref: "pref_ambulance"
      vg: "red_car"
    Granny: &P22
      state: "state_2_peach"
      goals: [ [ -3.5,-5.0 ], [ -7.0,-5.0 ] ]
      traj: "traj_1_3"
      pref: "cautious"
      vg: "green_car"
    Average: &P32
      state: "state_3_peach"
      goals: [ [ -15.0,13.5 ], [ -15.0,17 ] ]
      traj: "traj_1_3"
      pref: "common_person"
      vg: "blue_car"

# make sure the preferences here are a refinement of the ones above
ral_02_level_1:
  players:
    Ambulance:
      <<: *P12
      pref: "pref_ambulance_level_1"
    Granny:
      <<: *P22
      pref: "cautious"
    Average:
      <<: *P32
      pref: "common_person"


# make sure the preferences here are a refinement of the ones above
ral_02_level_2:
  players:
    Ambulance:
      <<: *P12
      pref: "pref_ambulance_level_2"
    Granny:
      <<: *P22
      pref: "cautious"
    Average:
      <<: *P32
      pref: "common_person"

####################################################################################

ral_03_level_0:
  players:
    Ambulance: &P23
      state: "state_1_peach"
      goals: [ [ -15.0,13.5 ], [ -15.0,17 ] ]
      traj: "traj_1_3"
      pref: "pref_ambulance"
      vg: "red_car"
    Granny: &P13
      state: "state_2_peach"
      goals: [ [ -3.5,-5.0 ], [ -7.0,-5.0 ] ]
      traj: "traj_1_3"
      pref: "cautious"
      vg: "green_car"
    Average: &P33
      state: "state_3_peach"
      goals: [ [ -15.0,13.5 ], [ -15.0,17 ] ]
      traj: "traj_1_3"
      pref: "common_person"
      vg: "blue_car"

# make sure the preferences here are a refinement of the ones above
ral_03_level_1:
  players:
    Ambulance:
      <<: *P23
      pref: "pref_ambulance_level_1"
    Granny:
      <<: *P13
      pref: "cautious"
    Average:
      <<: *P33
      pref: "common_person"


# make sure the preferences here are a refinement of the ones above
ral_03_level_2:
  players:
    Ambulance:
      <<: *P23
      pref: "pref_ambulance_level_2"
    Granny:
      <<: *P13
      pref: "cautious"
    Average:
      <<: *P33
      pref: "common_person"

####################################################################################

ral_04_level_0:
  players:
    Ambulance: &P34
      state: "state_1_peach"
      goals: [ [ -15.0,13.5 ], [ -15.0,17 ] ]
      traj: "traj_1_3"
      pref: "pref_ambulance"
      vg: "red_car"
    Granny: &P14
      state: "state_2_peach"
      goals: [ [ -3.5,-5.0 ], [ -7.0,-5.0 ] ]
      traj: "traj_1_3"
      pref: "cautious"
      vg: "green_car"
    Average: &P24
      state: "state_3_peach"
      goals: [ [ -15.0,13.5 ], [ -15.0,17 ] ]
      traj: "traj_1_3"
      pref: "common_person"
      vg: "blue_car"

# make sure the preferences here are a refinement of the ones above
ral_04_level_1:
  players:
    Ambulance:
      <<: *P34
      pref: "pref_ambulance_level_1"
    Granny:
      <<: *P14
      pref: "cautious"
    Average:
      <<: *P24
      pref: "common_person"


# make sure the preferences here are a refinement of the ones above
ral_04_level_2:
  players:
    Ambulance:
      <<: *P34
      pref: "pref_ambulance_level_2"
    Granny:
      <<: *P14
      pref: "cautious"
    Average:
      <<: *P24
      pref: "common_person"

