# Pref structure for each player
# Player_name:
#   node1:   List[None]
#   node2:   List[Parent1, Parent2, ...]
#   node3:   List[Parent1, Parent3, ...]
#     nodes    -> Any node from pref_nodes.yaml
#     Parents  -> Any node from pref_nodes.yaml

# Use "NoPreference" for any action

## Finite time preferences
pref_ambulance:
  CollisionEnergy: [ ]
  EpisodeTime: [ "CollisionEnergy" ]
  MinimumClearance: [ "EpisodeTime" ]
  DrivableAreaViolation: [ "EpisodeTime" ]
  DeviationHeading: [ "DrivableAreaViolation","MinimumClearance" ]

pref_ambulance_level_1:
  CollisionEnergy: [ ]
  EpisodeTime: [ "CollisionEnergy" ]
  MinimumClearance: [ "EpisodeTime" ]
  DrivableAreaViolation: [ "MinimumClearance" ]
  DeviationHeading: [ "DrivableAreaViolation" ]

pref_ambulance_level_2:
  CollisionEnergy: [ ]
  EpisodeTime: [ "CollisionEnergy" ]
  MinimumClearance: [ "EpisodeTime" ]
  DrivableAreaViolation: [ "MinimumClearance" ]
  DeviationHeading: [ "DrivableAreaViolation" ]
  weights_comf: [ "DeviationHeading" ]

pref_leon_dev:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  LateralComfort: [ "DrivableAreaViolation" ]

pref_leon_dev_1:
  CollisionEnergy: [ ]
  LateralComfort: [ "CollisionEnergy" ]
  DrivableAreaViolation: [ "LateralComfort" ]


pref_leon_dev_2:
  CollisionEnergy: [ ]
  LongitudinalAcceleration: [ "CollisionEnergy" ]
  SteeringRate: [ "CollisionEnergy" ]

pref_leon_dev_3:
  CollisionEnergy: [ ]
  DeviationLateral: [ "CollisionEnergy" ]
  DeviationHeading: [ "CollisionEnergy" ]

pref_leon_dev_4:
  ProgressAlongReference: [ ]
  DrivableAreaViolation: [ "ProgressAlongReference" ]
  CollisionEnergy: [ "DrivableAreaViolation" ]
  LateralComfort: [ "DrivableAreaViolation" ]

dev_commonroad_ego:
  DrivableAreaViolation: []
  CollisionEnergy: ["DrivableAreaViolation"]
  MinimumClearance: ["CollisionEnergy"]
  ProgressAlongReference: ["MinimumClearance"]

default_commonroad_ego:
  RoadCompliance_CR: []
  CollisionBool: []
  TR1: ["RoadCompliance_CR", "CollisionBool",]
  ProgressTowardsGoal: ["RoadCompliance_CR", "CollisionBool", ]

only_driving_area_violation:
  DrivableAreaViolation: []

only_collision:
  CollisionEnergy: []

dev_default_commonroad:
  CollisionEnergy: []
  MinimumClearance: ["CollisionEnergy"]
  DrivableAreaViolation: ["CollisionEnergy"]
  ProgressAlongReference: ["DrivableAreaViolation", "MinimumClearance"]

default_commonroad:
  TR1: []

pref_granny:
  CollisionEnergy: [ ]
  MinimumClearance: [ "CollisionEnergy" ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  LateralComfort: [ "DrivableAreaViolation", "MinimumClearance" ]
  DeviationHeading: [ "DrivableAreaViolation", "MinimumClearance" ]
  DeviationLateral: [ "DrivableAreaViolation", "MinimumClearance" ]
  EpisodeTime: [ "DeviationHeading", "DeviationLateral","LateralComfort" ]

pref_granny_level_1: # fixme this is not a refinement
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  MinimumClearance: [ "DrivableAreaViolation" ]
  LateralComfort: [ "DrivableAreaViolation" ]
  weights_5: [ "DrivableAreaViolation" ]
  EpisodeTime: [ "weights_5","LateralComfort" ]

pref_granny_level_2:
  CollisionEnergy: [ ]
  #todo

common_person:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  weights_speed: [ "DrivableAreaViolation" ]
  MinimumClearance: [ "DrivableAreaViolation" ]
  weights_5: [ "weights_speed", "MinimumClearance" ]
  LateralComfort: [ "weights_5" ]
  LongitudinalAcceleration: [ "weights_5" ]

common_person_2:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  weights_speed: [ "DrivableAreaViolation" ]
  MinimumClearance: [ "DrivableAreaViolation" ]
  weights_5: [ "weights_speed", "MinimumClearance" ]
  weights_comf: [ "weights_5" ]

common_person_3:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  MinimumClearance: [ "DrivableAreaViolation" ]
  weights_speed: [ "MinimumClearance" ]
  weights_5: [ "weights_speed" ]
  weights_comf: [ "weights_5" ]

common_person_4:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  MinimumClearance: [ "DrivableAreaViolation" ]
  weights_speed: [ "MinimumClearance" ]
  weights_comf_extreme: [ "weights_speed" ]

common_person_5:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  MinimumClearance: [ "DrivableAreaViolation" ]
  weights_comf_extreme_2: [ "MinimumClearance" ]

common_person_6:
  CollisionEnergy: [ ]
  weights_comf_extreme_3:      [ "CollisionEnergy" ]

common_person_7:
  CollisionEnergy: [ ]
  DrivableAreaViolation: ["CollisionEnergy"]
  weights_ral_1: ["DrivableAreaViolation"]
  weighted_ref_deviation: ["weights_ral_1"]
  weights_comf: ["weighted_ref_deviation"]

cautious:
  DrivableAreaViolation: [ ]
  CollisionEnergy: [ ]
  MinimumClearance: [ ]
  LateralComfort: [ "DrivableAreaViolation", "CollisionEnergy", "MinimumClearance" ]
  LongitudinalAcceleration: [ "DrivableAreaViolation", "CollisionEnergy", "MinimumClearance" ]
  EpisodeTime: [ "LateralComfort", "LongitudinalAcceleration" ]

cautious_1:
  DrivableAreaViolation: [ ]
  CollisionEnergy: [ ]
  MinimumClearance: [ ]

cautious_2:
  DrivableAreaViolation: [ ]
  CollisionEnergy: [ ]
  MinimumClearance: [ ]
  LateralComfort: [ "DrivableAreaViolation", "CollisionEnergy", "MinimumClearance" ]
  LongitudinalAcceleration: [ "DrivableAreaViolation", "CollisionEnergy", "MinimumClearance" ]

cautious_3:
  DrivableAreaViolation: [ ]
  CollisionEnergy: [ ]
  MinimumClearance: [ ]
  LateralComfort: [ "DrivableAreaViolation", "CollisionEnergy", "MinimumClearance" ]
  LongitudinalAcceleration: [ "DrivableAreaViolation", "CollisionEnergy", "MinimumClearance" ]
  EpisodeTime: [ "LateralComfort", "LongitudinalAcceleration" ]

suicidal:
  weigths_suicidal: [ ]

citizen_1:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  MinimumClearance: [ "CollisionEnergy" ]
  LateralComfort: [ "CollisionEnergy" ]
  LongitudinalAcceleration: [ "CollisionEnergy" ]
  EpisodeTime: [ "CollisionEnergy" ]
  DeviationHeading: [ "CollisionEnergy" ]
  DeviationLateral: [ "CollisionEnergy" ]

citizen_2:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  MinimumClearance: [ "CollisionEnergy" ]
  LateralComfort: [ "DrivableAreaViolation", "MinimumClearance" ]
  LongitudinalAcceleration: [ "DrivableAreaViolation", "MinimumClearance" ]
  EpisodeTime: [ "DrivableAreaViolation", "MinimumClearance" ]
  DeviationHeading: [ "DrivableAreaViolation", "MinimumClearance" ]
  DeviationLateral: [ "DrivableAreaViolation", "MinimumClearance" ]

citizen_2_1:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  MinimumClearance: [ "CollisionEnergy" ]
  LateralComfort: [ "DrivableAreaViolation", "MinimumClearance" ]
  LongitudinalAcceleration: [ "DrivableAreaViolation", "MinimumClearance" ]
  EpisodeTime: [ "DrivableAreaViolation", "MinimumClearance" ]
  weights_5: [ "EpisodeTime" ]

citizen_3:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  MinimumClearance: [ "CollisionEnergy" ]
  EpisodeTime: [ "DrivableAreaViolation", "MinimumClearance" ]
  LateralComfort: [ "EpisodeTime" ]
  LongitudinalAcceleration: [ "EpisodeTime" ]
  DeviationHeading: [ "EpisodeTime" ]
  DeviationLateral: [ "EpisodeTime" ]

citizen_4:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  MinimumClearance: [ "CollisionEnergy" ]
  EpisodeTime: [ "DrivableAreaViolation", "MinimumClearance" ]
  LateralComfort: [ "EpisodeTime" ]
  LongitudinalAcceleration: [ "EpisodeTime" ]
  DeviationHeading: [ "LateralComfort", "LongitudinalAcceleration" ]
  DeviationLateral: [ "LateralComfort", "LongitudinalAcceleration" ]

citizen_5:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  MinimumClearance: [ "CollisionEnergy" ]
  EpisodeTime: [ "DrivableAreaViolation", "MinimumClearance" ]
  LateralComfort: [ "EpisodeTime" ]
  LongitudinalAcceleration: [ "EpisodeTime" ]
  weights_5: [ "LateralComfort", "LongitudinalAcceleration" ]

citizen_5_bis:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  MinimumClearance: [ "CollisionEnergy" ]
  weights_speed: [ "DrivableAreaViolation", "MinimumClearance" ]
  LateralComfort: [ "weights_speed" ]
  LongitudinalAcceleration: [ "weights_speed" ]
  weights_5: [ "LateralComfort", "LongitudinalAcceleration" ]

citizen_6:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  MinimumClearance: [ "CollisionEnergy" ]
  EpisodeTime: [ "DrivableAreaViolation", "MinimumClearance" ]
  weights_comf: [ "EpisodeTime" ]
  weights_5: [ "weights_comf" ]

citizen_7:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  MinimumClearance: [ "CollisionEnergy" ]
  weights_speed: [ "DrivableAreaViolation", "MinimumClearance" ]
  weights_comf: [ "weights_speed" ]
  weights_5: [ "weights_comf" ]

citizen_8:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  MinimumClearance: [ "DrivableAreaViolation" ]
  weights_speed: [ "DrivableAreaViolation" ]
  weights_comf: [ "weights_speed" ]
  weights_5: [ "weights_comf" ]

citizen_9:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  MinimumClearance: [ "DrivableAreaViolation" ]
  weights_speed: [ "MinimumClearance" ]
  weights_comf: [ "weights_speed" ]
  weights_5: [ "weights_comf" ]

citizen_10:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  MinimumClearance: [ "DrivableAreaViolation" ]
  weights_speed: [ "MinimumClearance" ]
  weights_comf_extreme: [ "weights_speed" ]

citizen_11:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  MinimumClearance: [ "DrivableAreaViolation" ]
  weights_comf_extreme_2: [ "MinimumClearance" ]

citizen_12:
  CollisionEnergy: [ ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  MinimumClearance: [ "DrivableAreaViolation" ]
  EpisodeTime: ["MinimumClearance"]
  weights_comf: ["EpisodeTime"]
  weighted_ref_deviation: ["weights_comf"]

########################################################
pref_ambulance_az:
  CollisionEnergy: [ ]
  EpisodeTime: [ "CollisionEnergy" ]
  DrivableAreaViolation: [ "CollisionEnergy" ]
  MinimumClearance: [ "CollisionEnergy" ]
  LateralComfort: [ "DrivableAreaViolation", "MinimumClearance","EpisodeTime" ]
  LongitudinalAcceleration: [ "DrivableAreaViolation", "MinimumClearance","EpisodeTime" ]
  weighted_ref_deviation: [ "DrivableAreaViolation", "MinimumClearance","EpisodeTime" ]

pref_ambulance_az1:
  CollisionEnergy: [ ]
  EpisodeTime: [ "CollisionEnergy" ]
  DrivableAreaViolation: [ "EpisodeTime" ]
  MinimumClearance: [ "EpisodeTime" ]
  weights_comf: [ "DrivableAreaViolation", "MinimumClearance", ]
  weighted_ref_deviation: [ "DrivableAreaViolation", "MinimumClearance", ]

pref_ambulance_az2:
  CollisionEnergy: [ ]
  EpisodeTime: [ "CollisionEnergy" ]
  MinimumClearance: [ "EpisodeTime" ]
  DrivableAreaViolation: [ "MinimumClearance" ]
  weights_comf: [ "DrivableAreaViolation" ]
  weighted_ref_deviation: [ "weights_comf", ]

# Test Preferences
test_1:                       &test_1
  CollisionEnergy:            []
  ProgressAlongReference:     ["CollisionEnergy"]
  DrivableAreaViolation:      ["CollisionEnergy"]
  LateralComfort:             ["CollisionEnergy"]
  DeviationLateral:           ["ProgressAlongReference"]

test_2:                       &test_2
  <<: *test_1
  DeviationHeading:           ["DeviationLateral"]
  MinimumClearance:           ["DrivableAreaViolation", "DeviationHeading"]
  LongitudinalAcceleration:   ["LateralComfort", "MinimumClearance"]

test_3:                       &test_3
  <<: *test_2
  EpisodeTime:                ["LateralComfort"]
  SteeringRate:               ["DrivableAreaViolation", "EpisodeTime"]
  SteeringAngle:              ["ProgressAlongReference", "SteeringRate"]